# Generated by Django 4.1 on 2022-10-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_order_order_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, to='api.orderitem'),
        ),
    ]
